name: yabwe
description: Wrap of Medium.com WYSIWYG editor clone. Uses contenteditable API to implement a rich text solution.
version: 0.0.2
homepage: https://lefty.io
author: Kevin Segaud <segaud.kevin@gmail.com>

environment:
  sdk: '>=1.20.1 <3.0.0'

dependencies:
  dart_browser_loader: ^0.0.4
  js: ^0.6.1

dev_dependencies:
  test: ^1.3.0
